### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by 0000070** [LokerL/tts-vue#147]
#### Describe the problem you confuse
出现这种报错怎么处理呢？发生在第7次转换时，未完成，并报错
[2023-10-03 19:23:08.795] [error] Error: Speech invocation failed after 10 retries
    at kf (file:///D:/Program%20Files/tts-vue/resources/app.asar/dist/index.1a008108.js:26:356)
    at async Yi (file:///D:/Program%20Files/tts-vue/resources/app.asar/dist/index.1a008108.js:26:64)
    at async Proxy.start (file:///D:/Program%20Files/tts-vue/resources/app.asar/dist/index.1a008108.js:81:586)

**Comment by 0000070** [comment]
此报错为使用软件生成转换时的日志

**Comment by IamBigSun** [comment]
150行文字，每行30个字左右，要么是 [error] Error: Speech invocation failed after undefined retries
要么就是只转移4~5分钟(我这里总共转完可能要9~10分钟)。 无论是批量转换还是文本框，都不行。有时候还提示network error.
开代理和不开代理都这样。咋回事啊？谁能给解释下
