### ISSUE TITLE
您好，在MACOS上打包失败了 能否提供MACOS上的应用

### ISSUE THREAD

**Issue by evilvlso** [LokerL/tts-vue#68]
#### Describe the problem you confuse
您好，我下载完源码，尝试以下三条命令，在第二条命令中出现错误，如下
`npm i`
`npm run dev`
`npm  run build`

```
failed to load config from /Users/dongzai/Downloads/tts-vue-1.8.7/vite.config.ts
error during build:
TypeError: (0 , import_fs.rmSync) is not a function
    at Object.<anonymous> (/Users/dongzai/Downloads/tts-vue-1.8.7/vite.config.ts:87:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.require.extensions.<computed> [as .ts] (/Users/dongzai/Downloads/tts-vue-1.8.7/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61998:20)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at loadConfigFromBundledFile (/Users/dongzai/Downloads/tts-vue-1.8.7/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:62006:17)
    at loadConfigFromFile (/Users/dongzai/Downloads/tts-vue-1.8.7/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:61925:32)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
看不太懂这个报错，您能提供下MACOS上的应用呢？或者您告诉我解决方法 我去搞定

**Comment by LokerL** [comment]
如果install过程没有错误的话，可能是node或者electron版本问题
