### ISSUE TITLE
[Bug] 报错：Invalid handshake: invalid first line format

### ISSUE THREAD

**Issue by HorsenLiu** [LokerL/tts-vue#74]
### 环境
- 操作系统：Windows 10 22H2 (19045.2486)
- 软件版本：1.8.7

### 报错信息
```text
node:events:504 Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (D:\Setup\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (D:\Setup\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (D:\Setup\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (D:\Setup\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
![image](https://user-images.githubusercontent.com/50764745/218806762-3203902b-628c-4cd1-b900-536a0642f3b8.png)

### 描述
可能是我反复试听，反复提交，然后把接口搞坏了？

**Comment by Awei097** [comment]
报错。
node:events:504 Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (C:\Program Files\tts…onnection.js:375:22)
    at Connection.readHandshake (C:\Program Files\tts…onnection.js:331:54)
    at Connection.doRead (C:\Program Files\tts…onnection.js:246:13)
    at TLSSocket.<anonymous> (C:\Program Files\tts…\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by LokerL** [comment]
可能是微信那边对接口限制。。。

**Comment by LiuMenglei-dobest** [comment]
我也遇到了同样的问题
