### ISSUE TITLE
[Bug] invalid first line format

### ISSUE THREAD

**Issue by ethan0913** [LokerL/tts-vue#84]
Uncaught Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (F:\yuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:375:22)
    at Connection.readHandshake (F:\yuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:331:54)
    at Connection.doRead (F:\yuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:246:13)
    at TLSSocket.<anonymous> (F:\yuyin\tts-vue\resources\app.asar\node_modules\nodejs-websocket\Connection.js:66:8)
    at TLSSocket.emit (node:events:526:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by LokerL** [comment]
已更新
